parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/36.h>
    #define CONFIG_WIRELESS

  raw_binding_map:
    "&bootloader": {t: '$$mdi:progress-download$$', s: Boot}
    "&sys_reset": {t: '$$mdi:restart$$', s: Reset}
    "&caps_word": Caps Word
    "&kp LA(F4)": Close

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4

    "&kp LC(C)": $$mdi:content-copy$$
    "&kp LC(X)": $$mdi:content-cut$$
    "&kp LC(V)": $$mdi:content-paste$$

    "&kp LC(Z)": $$mdi:undo-variant$$
    "&kp LC(LS(Z))": $$mdi:redo-variant$$
  
    "&kp LG(LC(LEFT))": PDesk
    "&kp LG(LC(RIGHT))": NDesk
    "&kp LG(LC(LS(A)))": PinA.
    "&kp LG(LC(LS(Q)))": PinW.
    "&kp LC(F)": $$mdi:magnify$$

    "&kp LS(LBKT)": "{"
    "&kp LS(RBKT)": "}"

    "&swapper": NWin
    # "&kp LS(TAB)": PWin 
    "&dot_spc": Sentence
    "&num_dance": { "t": "Smart"}
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&thumb_magic_1 LSHFT 0": { "t": Magic, "h": "Shift" }
    "&smart_mouse": Smart Mouse
    "&t_btick": "```"
    "&select_all": "SLC ALL"
    "&select_none": "SLC NONE"
    "&select_word": "SLC WRD"
    "&extend_word": "EXT WRD"
    "&select_line": "SLC LINE"
    "&extend_line": "EXT LINE"

    "&hml LS(LALT)TAB": Tab
    "&hm_combo_ldr": Leader
    "&hm_combo_ldrsh": Shift+Leader
    "&hm_combo_lpar": { "t": "< (" }
    "&hm_combo_rpar": { "t": "> )"}
    "&kp LBKT": { "t": "["}
    "&kp RBKT": { "t": "]"}

    "&mmv MOVE_UP": Mouse ↑
    "&mmv MOVE_DOWN": Mouse ↓
    "&mmv MOVE_LEFT": Mouse ←
    "&mmv MOVE_RIGHT": Mouse →

    "&msc SCRL_UP": Scroll ↑
    "&msc SCRL_DOWN": Scroll ↓
    "&msc SCRL_LEFT": Scroll ←
    "&msc SCRL_RIGHT": Scroll →

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click
    "&mkp MB4": Back Click
    "&mkp MB5": Forward Click

    "&sqt_dqt": {t: '''', s: '"'}
    "&minus_slash": {t: '-', s: '/'}
    "&dot_qmark": {t: '.', s: '?'}
    "&comma_excl": {t: ',', s: '!'}
    "&bspc_del": {t: '$$mdi:backspace$$', s: '$$mdi:backspace-reverse$$'}
    "&undo_redo": {t: '$$mdi:undo$$', s: '$$mdi:redo$$'}
    "&copy_cut": {t: '$$mdi:content-copy$$', s: '$$mdi:content-cut$$'}
    "&v_comma_excl": {t: ',', s: '!'}
    "&v_dot_qmark": {t: '.', s: '?'}
    "&thumb_bspc LSHFT 0": {t: '$$mdi:backspace$$', h: '$$mdi:arrow-up-bold$$', s: '$$mdi:backspace-reverse$$'}
    "&nav_ht NAV 0": {t: '$$mdi:keyboard-esc$$', h: Nav, s: '$$mdi:keyboard-tab$$'}
    # "&thumb_spc NUM SPACE": {t: '$$mdi:keyboard-space$$', h: Symbol}
    # "&lt NUM RET": {t: '$$mdi:keyboard-return$$', h: Num}
    # "&lt NAV BSPC": {t: '$$mdi:backspace$$', h: Nav}
    # "&num_repeat NUM 0": {t: '$$mdi:repeat$$', h: Num}
    # "&sturdy_num_repeat NUM 0": {t: '$$mdi:repeat$$', h: Num}
    # "&thumb_magic_1 LSHFT 0": {t: '$$mdi:arrow-up-bold$$'}
    # "&nav_repeat NUM 0": {t: '$$mdi:repeat$$', h: Num}
    # "&tog MOUSE": {t: Mouse, type: layer-activator}
    # "&mouse_ht MOUSE MOUSE": {t: Mouse, type: layer-activator}
    # "&to_graphite": {t: Graphite, type: layer-activator}
    "&thumb_r SYM R": {t: R, h: Symbol}
    "&nav_repeat NAV 0": {t: '$$mdi:repeat$$', h: Nav}
    "&alpha_magic_racket_1": {t: '$$mdi:star-four-points$$'}
    "&alpha_magic_sturdy": {t: '$$mdi:star-four-points$$'}
    "&graphite_bigram_d": {t: D}
    "&graphite_bigram_o": {t: O}
    "&graphite_bigram_x": {t: X}
    "&graphite_bigram_q": {t: Q}
    "&graphite_hml_n LGUI": {t: N, h: ❖}
    "&graphite_hml_n LGUI 0": {t: N, h: ❖}
    "&graphite_hml_r LALT": {t: R, h: ⌥}
    "&graphite_hml_r LALT 0": {t: R, h: ⌥}
    "&to_racket": {t: Racket, type: layer-activator}
    "&to_sturdy": {t: Sturdy, type: layer-activator}
    "&to_vestnik": {t: Vestnik, type: layer-activator}
    # "&sl FUN": {t: Fn}
    # "&sl SYS": {t: System, type: layer-activator}
    "&soft_off": {t: '$$mdi:keyboard-off-outline$$'}
    "&lang_en": {t: EN}
    "&lang_ru": {t: RU}
    "&bt_0": {t: BT 0}
    "&bt_1": {t: BT 1}
    "&bt_2": {t: BT 2}
    "&bt_3": {t: BT 3}
    "&kp LC(LS(TAB))": {t: Tab ←}
    "&kp LC(TAB)": {t: Tab →}
    "&kp LC(LS(LBKT))": {t: Tab ←}
    "&kp LC(LS(RBKT))": {t: Tab →}
    "&kp LC(A)": {t: Tmux}
    "&kp _SCR_AREA": {t: '$$mdi:crop$$', s: Scr}
    "&kp _SCR_FULL": {t: '$$mdi:monitor-screenshot$$', s: Scr}
    "&kp _SHUTDOWN": {t: '$$mdi:power$$'}
    "&kp C_POWER": {t: '$$mdi:power$$'}
    "&kp K_POWER": {t: '$$mdi:power$$'}
    "&kp _LOCK": {t: '$$mdi:lock$$'}
    "&kp LG(LS(L))": {t: '$$mdi:lock$$'}
    "&kp LG(L)": {t: '$$mdi:lock$$'}
    "&kp C_SLEEP": {t: '$$mdi:moon-waning-crescent$$'}
    "&kp C_MUTE": {t: '$$mdi:volume-mute$$'}
    "&kp C_PP": {t: '$$mdi:play-pause$$'}
    "&kp C_PREV": {t: '$$mdi:skip-previous$$'}
    "&kp C_NEXT": {t: '$$mdi:skip-next$$'}
    "&kp LG(F9)": {t: '$$mdi:microphone-off$$'}
    "&kp LG(O)": {t: Space ←}
    "&kp LG(U)": {t: Space →}
    "&kp LG(LA(S))": {t: STT}

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_ldrsh: { align: top, o: 1.35 }

    combo_lt: { hidden: true }
    combo_gt: { hidden: true }
    combo_lbrc: { hidden: true }
    combo_rbrc: { hidden: true }

  zmk_keycode_map:
    # custom mappings
    LALT: Alt
    RALT: Alt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    BSPC: Bspc
    DEL: Del
    ESC: Esc
    RET: Enter
    SPACE: Spc
    TAB: Tab

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    K_CANCEL: Cancel

    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _
    

draw_config:
  append_colon_to_layer_header: false
  dark_mode: false
  # footer_text: "urob/zmk-config"
  glyph_tap_size: 15
  glyph_hold_size: 12
  glyph_shifted_size: 10
  legend_rel_y: 1
  outer_pad_w: 10
  outer_pad_h: 10
  small_pad: 4

  svg_style: |
    svg path { fill: inherit; }

    svg.keymap {
        --color-bg:      #7c6f64;
        --color-key:     #fbf1c7;
        --color-text:    #3c3836;
        --color-ghost:   #928374;
        --color-dendron: #d5c4a1;
        --color-held:    #bdae93;

        --color-fn:      #458588;
        --color-nav:     #d79921;
        --color-num:     #d65d0e;
        --color-sys:     #689d6a;

        fill: var(--color-text);
        background-color: var(--color-bg);
        font-family: Calibri, system-ui, sans-serif;
        font-size: 16px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        letter-spacing: 0.02em;
    }

    text.tap     { font-weight: 500; }
    text.hold    { font-weight: 400; font-size: 13px; }
    text.shifted { font-weight: 400; font-size: 11px; }
    text.combo, text.left, text.right, text.tl, text.tr, text.bl, text.br { font-size: 10px; }

    text.hold, text.bl, text.br    { text-anchor: middle; dominant-baseline: auto; }
    text.shifted, text.tl, text.tr { text-anchor: middle; dominant-baseline: hanging; }
    text.left, text.tl, text.bl    { text-anchor: start; }
    text.right, text.tr, text.br   { text-anchor: end; }

    text.layer-activator { text-decoration: underline; }
    text.combo.hold, text.combo.shifted, text.combo.left, text.combo.right { font-size: 8px; }

    text.label, text.footer {
        fill: var(--color-key);
        stroke: var(--color-bg);
        stroke-width: 4;
        paint-order: stroke;
    }
    text.label  { font-weight: bold; text-anchor: start; }
    text.footer { text-anchor: end; dominant-baseline: auto; }

    rect.key, rect.combo, rect.combo-separate { fill: var(--color-key); stroke-width: 0; }
    rect.held, rect.combo.held                { fill: var(--color-held); }
    .layer-Combos rect.key                    { fill: var(--color-ghost); }

    path.combo { stroke: var(--color-dendron); stroke-width: 2; stroke-dasharray: 2, 3; opacity: 0.45; fill: none; }

    text.tl, use.tl { fill: var(--color-fn); }
    text.tr, use.tr { fill: var(--color-nav); }
    text.bl, use.bl { fill: var(--color-num); }
    text.br, use.br { fill: var(--color-sys); }

    .keypos-42 text.hold { fill: var(--color-nav); }
    .keypos-44 text.hold { fill: var(--color-fn); }
    .keypos-40 text.hold { fill: var(--color-num); font-size: 15px; }
    .keypos-40 text.tap  { fill: var(--color-num); }
    .keypos-43 text.hold { font-size: 15px; }

    .icon-tabler > path                             { fill: inherit; stroke: inherit; stroke-width: 2; }
    .icon-tabler > path[stroke="none"][fill="none"] { visibility: hidden; }

    @media (prefers-color-scheme: dark) {
        svg.keymap {
            --color-bg:      #a89984;
            --color-key:     #282828;
            --color-text:    #ebdbb2;
            --color-ghost:   #928374;
            --color-dendron: #504945;
            --color-held:    #665c54;

            --color-fn:      #458588;
            --color-nav:     #fabd2f;
            --color-num:     #d65d0e;
            --color-sys:     #689d6a;
        }
    }
